
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 12 19:19:27 CDT 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Mayor_que = 69;
  public static final int Parentesis_c = 84;
  public static final int Public = 39;
  public static final int Return = 6;
  public static final int Parentesis_a = 83;
  public static final int Llave_c = 86;
  public static final int Incremento = 65;
  public static final int Llave_a = 85;
  public static final int Console = 11;
  public static final int Coma = 94;
  public static final int Break = 59;
  public static final int Corchete_c = 88;
  public static final int Comilla = 92;
  public static final int Corchete_a = 87;
  public static final int True = 36;
  public static final int Long = 33;
  public static final int Punto = 93;
  public static final int Default = 25;
  public static final int Import = 47;
  public static final int Print = 44;
  public static final int Char = 28;
  public static final int NextFloat = 55;
  public static final int Decremento = 66;
  public static final int Resta_combinada = 75;
  public static final int For = 5;
  public static final int Mayor_o_igual = 73;
  public static final int Void = 46;
  public static final int Else = 4;
  public static final int Residuo_combinado = 78;
  public static final int Try = 19;
  public static final int Resta = 62;
  public static final int Int = 2;
  public static final int Null = 38;
  public static final int NOT = 80;
  public static final int This = 24;
  public static final int Suma = 61;
  public static final int ERROR = 98;
  public static final int Main = 8;
  public static final int String = 27;
  public static final int NextLong = 57;
  public static final int Do = 21;
  public static final int Set = 15;
  public static final int Static = 50;
  public static final int Producto_combinado = 76;
  public static final int Private = 41;
  public static final int P_coma = 89;
  public static final int Function = 12;
  public static final int Residuo = 67;
  public static final int Short = 30;
  public static final int NextDouble = 54;
  public static final int Case = 7;
  public static final int NextInt = 53;
  public static final int New = 16;
  public static final int Document = 20;
  public static final int Const = 13;
  public static final int SYstem = 42;
  public static final int Continue = 17;
  public static final int Byte = 29;
  public static final int In = 18;
  public static final int InstanceOf = 52;
  public static final int With = 26;
  public static final int If = 3;
  public static final int Suma_combinada = 74;
  public static final int Igual_que = 70;
  public static final int EOF = 0;
  public static final int Division_combinada = 77;
  public static final int Numero = 96;
  public static final int Double = 31;
  public static final int Division = 64;
  public static final int Package = 49;
  public static final int Dos_puntos = 90;
  public static final int OR = 81;
  public static final int error = 1;
  public static final int False = 37;
  public static final int Get = 14;
  public static final int SCanner = 48;
  public static final int Next = 58;
  public static final int Comillas = 91;
  public static final int Final = 35;
  public static final int Float = 32;
  public static final int Menor_que = 68;
  public static final int NextByte = 56;
  public static final int Distinto_que = 71;
  public static final int Identificador = 95;
  public static final int Println = 43;
  public static final int Negacion = 79;
  public static final int Menor_o_igual = 72;
  public static final int Class = 9;
  public static final int Super = 51;
  public static final int Out = 45;
  public static final int TS = 97;
  public static final int AND = 82;
  public static final int Delete = 23;
  public static final int Igual = 60;
  public static final int While = 22;
  public static final int Boolean = 34;
  public static final int Multiplicacion = 63;
  public static final int Switch = 10;
  public static final int Protected = 40;
}

